version: '3.8'

services:
  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-app
    volumes:
      - ./data:/app/data
    ports:
      - "5555:5555"
      - "8501:8501"
      - "8502:8502"
    depends_on:
      - graphdb
    environment:
      - GRAPHDB_URL=http://graphdb:7200
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    networks:
      - app-network

  vuejs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vuejs-app
    ports:
      - "8080:8080"
    depends_on:
      - flask-app
    networks:
      - app-network

  graphdb:
    image: ontotext/graphdb:10.8.0
    container_name: graphdb
    ports:
      - "7200:7200"
    command: >
          -Dgraphdb.workbench.cors.enable=true
          -Dgraphdb.workbench.cors.origin=*
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
